### ISSUE TITLE
oommfc.test() tornado conda error

### ISSUE THREAD

**Issue by gsabo** [ubermag/help#69] opened 2020-05-25 16:53 UTC
I have used Anaconda3-2020.02-Linux-x86_64.sh, the Linux Python 3.7 64-Bit (x86) installer, that is currently at [1].

This to report  the following error from the terminal command: 
python3 -c "import oommfc; oommfc.test()"

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/oommfc/__init__.py", line 3, in <module>
    import oommfc.oommf
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/oommfc/oommf/__init__.py", line 1, in <module>
    from .oommf import OOMMFRunner, TclOOMMFRunner, ExeOOMMFRunner, \
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/oommfc/oommf/oommf.py", line 11, in <module>
    import micromagneticmodel as mm
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/micromagneticmodel/__init__.py", line 5, in <module>
    import micromagneticmodel.examples
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/micromagneticmodel/examples/__init__.py", line 1, in <module>
    from .examples import macrospin
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/micromagneticmodel/examples/examples.py", line 1, in <module>
    import discretisedfield as df
  File "/home/username/anaconda3/envs/env4ubermag/lib/python3.6/site-packages/discretisedfield/__init__.py", line 12, in <module>
    __dependencies__ = pkg_resources.require(__name__)
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tornado 6.0.1 (/home/username/.local/lib/python3.6/site-packages), Requirement.parse('tornado!=6.0.0,!=6.0.1,!=6.0.2'), {'jupyterlab'})

I'm able to workaround the error by using:

conda install tornado=6.0.2

However, it is failing with the above error with tornado 6.0.4 that gets installed using "conda install ubermag -c conda-forge".

[1] https://www.anaconda.com/products/individual

**Comment by marijanbeg** [comment] 2020-05-26 20:08
Hi @gsabo, I am sorry you encountered this issue. It seems something went wrong with Jupyter installation. Can you try to install `discretisedfield` again?

```
conda install --channel conda-forge discretisedfield
```

This should install all Jupyter dependencies again. Please let me know if this does not solve the problem.

**Comment by gsabo** [comment] 2020-05-27 02:09
@marijanbeg, 

I tried it, but it still gives the same tornado VersionConflict error message as shown below.  I'm not familiar with how package dependencies are setup in the source code for conda.  Though, the problem seems related to how when ubermag is installed with "conda install ubermag -c conda-forge", it installs tornado 6.0.4 (instead of tornado 6.0.2) which then does not meet the dependency needed for jupyterlab as shown below. 

The oommfc.test() of course works fine if I manually install tornado 6.0.2 using the following conda install command.  

```
conda install tornado=6.0.2
```

This not a problem for me, but I could see it being an issue to newbies that are interested in using your ubermag as that is not a step in your install [documentation](https://ubermag.readthedocs.io/en/latest/ipynb/01-tutorial-installation.html). Thanks, Gavin

```
(ubermagenv) username@computername:~/Desktop$ conda install --channel conda-forge discretisedfield
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.
```

```
(ubermagenv) username@computername:~/Desktop$ python3 -c "import oommfc; oommfc.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/username/anaconda3/envs/ubermagenv/lib/python3.6/site-packages/oommfc/__init__.py", line 3, in <module>
    import oommfc.oommf
  File "/home/username/anaconda3/envs/ubermagenv/lib/python3.6/site-packages/oommfc/oommf/__init__.py", line 1, in <module>
    from .oommf import OOMMFRunner, TclOOMMFRunner, ExeOOMMFRunner, \
  File "/home/username/anaconda3/envs/ubermagenv/lib/python3.6/site-packages/oommfc/oommf/oommf.py", line 11, in <module>
    import micromagneticmodel as mm
  File "/home/username/anaconda3/envs/ubermagenv/lib/python3.6/site-packages/micromagneticmodel/__init__.py", line 5, in <module>
    import micromagneticmodel.examples
  File "/home/username/anaconda3/envs/ubermagenv/lib/python3.6/site-packages/micromagneticmodel/examples/__init__.py", line 1, in <module>
    from .examples import macrospin
  File "/home/username/anaconda3/envs/ubermagenv/lib/python3.6/site-packages/micromagneticmodel/examples/examples.py", line 1, in <module>
    import discretisedfield as df
  File "/home/username/anaconda3/envs/ubermagenv/lib/python3.6/site-packages/discretisedfield/__init__.py", line 12, in <module>
    __dependencies__ = pkg_resources.require(__name__)
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tornado 6.0.1 (/home/username/.local/lib/python3.6/site-packages), Requirement.parse('tornado!=6.0.0,!=6.0.1,!=6.0.2'), {'jupyterlab'})
```

```
(ubermagenv) username@computername:~/Desktop$ conda list | grep tornado
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
```

```
(ubermagenv) username@computername:~/Desktop$ conda search jupyterlab=2.1.3 --info
Loading channels: done
jupyterlab 2.1.3 py_0
---------------------
file name   : jupyterlab-2.1.3-py_0.tar.bz2
name        : jupyterlab
version     : 2.1.3
build       : py_0
build number: 0
size        : 5.9 MB
license     : BSD-3-Clause
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/jupyterlab-2.1.3-py_0.tar.bz2
md5         : cfd55b04d8fcb9f9bad52cf37a3c3016
timestamp   : 2020-05-23 12:18:53 UTC
dependencies: 
  - jinja2 >=2.10
  - jupyterlab_server >=1.1.0,<2.0.0
  - notebook >=4.3.1
  - python >=3.5
  - tornado !=6.0.0,!=6.0.1,!=6.0.2
```

**Comment by marijanbeg** [comment] 2020-05-27 10:12
Hi @gsabo, thank you for the clarification. The dependency of ubermag is `jupyterlab`. This effectively means that `jupyterlab` is installed together with all its dependencies as specified by `jupyterlab` package.

There seems to be a dependencies conflict within a `jupyterlab` package itself, which is most probably going to be fixed by Jupyter people soon. (That is why I asked you to install `discretisedfield` again, thinking that a new `jupyterlab` conds package has been built in the meantime). As you suggest, we could set a version of `tornado` in `ubermag` package recipe, but then there is a question then for how long this fix will work. I will monitor this issue over the next few days/weeks and see how we can proceed.

Thank you again for pointing this issue to us. If there is anything else we can help with, please let us know. (I will keep this issue open until the problem is fully resolved)

**Comment by marijanbeg** [comment] 2020-06-19 12:25
This issue should be resolved with newest ubermag. Please update using `conda update ubermag`

**Closed by marijanbeg** 2020-06-19 12:25 UTC
